AxelApen/AxelApen/Models/VEHICULO.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxelApen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        public string MATRICULA { get; set; }
        public string TIPO_VEHICULO { get; set; }
        public string MODELO { get; set; }
        public string MARCA { get; set; }
        public string LINEA { get; set; }
        public string PROPIETARIO { get; set; }
    }
}

AxelApen/AxelApen/Models/viewModel/Vehiculo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AxelApen.Models.viewModel
{
    public class Vehiculo
    {
        public String matricula { get; set; }
        public String tipoVehiculo { get; set; }
        public String modelo { get; set; }
        public String marca { get; set; }
        public String linea { get; set; }
        public String propietario { get; set; }

    }
}

AxelApen/AxelApen/Models/viewModel/VehiculoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AxelApen.Models.viewModel
{
    public class VehiculoViewModel
    {
        [Required]
        [StringLength(15)]
        public String matricula { get; set; }
        [Required]
        [StringLength(2)]
        public String tipoVehiculo { get; set; }
        [Required]
        [StringLength(15)]
        public String modelo { get; set; }
        [Required]
        [StringLength(10)]
        public String marca { get; set; }
        [Required]
        [StringLength(10)]
        public String linea { get; set; }
        [Required]
        [StringLength(100)]
        public String propietario { get; set; }
    }
}

AxelApen/AxelApen/Controllers/VehiculoController.cs
using AxelApen.Models;
using AxelApen.Models.viewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AxelApen.Controllers
{
    public class VehiculoController : Controller
    {
        // GET: Vehiculo
        public ActionResult Index()
        {

            List<Vehiculo> listaVehiculo;
            using (dbPruebaDesarrolloEntities bd = new dbPruebaDesarrolloEntities())
            {
                listaVehiculo = (from veh in bd.VEHICULO
                                 select new Vehiculo
                                 {
                                     matricula = veh.MATRICULA,
                                     tipoVehiculo = veh.TIPO_VEHICULO,
                                     modelo = veh.MODELO,
                                     marca = veh.MARCA,
                                     linea = veh.LINEA,
                                     propietario = veh.PROPIETARIO
                                 }


                    ).ToList();
            }
            return View(listaVehiculo);
        }

        public ActionResult Nuevo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(VehiculoViewModel model)
        {
            using (dbPruebaDesarrolloEntities db = new dbPruebaDesarrolloEntities())
            {
                var vehiculo = new VEHICULO();
                vehiculo.MATRICULA = model.matricula;
                vehiculo.TIPO_VEHICULO = model.tipoVehiculo;
                vehiculo.MODELO = model.modelo;
                vehiculo.MARCA = model.marca;
                vehiculo.LINEA = model.linea;
                vehiculo.PROPIETARIO = model.propietario;
                db.VEHICULO.Add(vehiculo);
                db.SaveChanges();

            }
            return Redirect("~/Vehiculo/");
        }

      
        public ActionResult Editar(string id)
        {
            VehiculoViewModel model = new VehiculoViewModel();

            using (dbPruebaDesarrolloEntities bd = new dbPruebaDesarrolloEntities())
            {
                var vehiculo = bd.VEHICULO.Find(id);
                model.matricula = vehiculo.MATRICULA;
                model.tipoVehiculo = vehiculo.TIPO_VEHICULO;
                model.modelo = vehiculo.MODELO;
                model.marca = vehiculo.MARCA;
                model.linea = vehiculo.LINEA;
                model.propietario = vehiculo.PROPIETARIO;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(VehiculoViewModel model)
        {
            using (dbPruebaDesarrolloEntities bd = new dbPruebaDesarrolloEntities())
            {
                var vehiculo = bd.VEHICULO.Find(model.matricula);
                vehiculo.TIPO_VEHICULO = model.tipoVehiculo;
                vehiculo.MODELO = model.modelo;
                vehiculo.MARCA = model.marca;
                vehiculo.LINEA = model.linea;
                vehiculo.PROPIETARIO = model.propietario;
                bd.Entry(vehiculo).State = System.Data.Entity.EntityState.Modified;
                bd.SaveChanges();

            }
            return Redirect("~/Vehiculo/");

        }

        public ActionResult Eliminar(string id)
        {
            using (dbPruebaDesarrolloEntities bd = new dbPruebaDesarrolloEntities())
            {
                var veh = bd.VEHICULO.Find(id);
                    bd.VEHICULO.Remove(veh);
                bd.SaveChanges();
                
            }
               return Redirect("~/Vehiculo/");
        }
    }
    }

AxelApen/AxelApen/Views/Vehiculo/Editar.cshtml
@model AxelApen.Models.viewModel.VehiculoViewModel
@{
    ViewBag.Title = "Editar Vehiculo";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Editar", "Vehiculo", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            <div>
                @Html.Label("MATRICULA")
                @Html.TextBoxFor(d => d.matricula, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.matricula, "", new { @class = "red" })

            </div>

            <div>
                @Html.Label("TIPO VEHICULO")
                @Html.TextBoxFor(d => d.tipoVehiculo, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.tipoVehiculo, "", new { @class = "red" })

            </div>

            <div>
                @Html.Label("MODELO")
                @Html.TextBoxFor(d => d.modelo, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.modelo, "", new { @class = "red" })

            </div>

            <div>
                @Html.Label("MARCA")
                @Html.TextBoxFor(d => d.marca, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.marca, "", new { @class = "red" })

            </div>

            <div>
                @Html.Label("LINEA")
                @Html.TextBoxFor(d => d.linea, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.linea, "", new { @class = "red" })

            </div>

            <div>
                @Html.Label("PROPIETARIO")
                @Html.TextBoxFor(d => d.propietario, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.propietario, "", new { @class = "red" })

            </div>

            <div>
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>

        </div>

    </div>

}

AxelApen/AxelApen/Views/Vehiculo/Index.cshtml
@model List<AxelApen.Models.viewModel.Vehiculo>
@{
    ViewBag.Title = "Vehiculo";
}

<h2>@ViewBag.Title</h2>

<div style="text-align:right; padding:5px">

    <a href="~/Vehiculo/Nuevo" class="btn btn-primary">Nuevo</a>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>MATRICULA</th>
                <th>TIPO VEHICULO</th>
                <th>MODELO</th>
                <th>MARCA</th>
                <th>LINEA</th>
                <th>PROPIETARIO</th>
                <th>OPCIONES</th>
            </tr>
@foreach(var vehiculo in Model)
{
    <tr>
        <td>@vehiculo.matricula</td>
        <td>@vehiculo.tipoVehiculo</td>
        <td>@vehiculo.modelo</td>
        <td>@vehiculo.marca</td>
        <td>@vehiculo.linea</td>
        <td>@vehiculo.propietario</td>
        <td>
            <a href="~/Vehiculo/Editar/@vehiculo.matricula" class="btn btn-default" >Editar</a>
            <a href="~/Vehiculo/Eliminar/@vehiculo.matricula" class="btn btn-danger">Eliminar</a>
        </td>
    </tr>
}

        </table>

    </div>

</div>

AxelApen/AxelApen/Views/Vehiculo/Nuevo.cshtml
@model AxelApen.Models.viewModel.VehiculoViewModel
@{
    ViewBag.Title = "Nuevo Vehiculo";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Nuevo", "Vehiculo", FormMethod.Post)) { 
<div class="row">
    <div class="col-md-12">
        <div>
            @Html.Label("MATRICULA")
            @Html.TextBoxFor(d=> d.matricula,"", new {@class="form-control"})
            @Html.ValidationMessageFor(d=> d.matricula, "", new {@class="red" })

        </div>

        <div>
            @Html.Label("TIPO VEHICULO")
            @Html.TextBoxFor(d => d.tipoVehiculo, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.tipoVehiculo, "", new { @class = "red" })

        </div>

        <div>
            @Html.Label("MODELO")
            @Html.TextBoxFor(d => d.modelo, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.modelo, "", new { @class = "red" })

        </div>

        <div>
            @Html.Label("MARCA")
            @Html.TextBoxFor(d => d.marca, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.marca, "", new { @class = "red" })

        </div>

        <div>
            @Html.Label("LINEA")
            @Html.TextBoxFor(d => d.linea, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.linea, "", new { @class = "red" })

        </div>

        <div>
            @Html.Label("PROPIETARIO")
            @Html.TextBoxFor(d => d.propietario, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.propietario, "", new { @class = "red" })

        </div>

        <div>
            <input value="Guardar" class="btn btn-primary" type="submit" />
        </div>

    </div>

</div>

}